### ISSUE TITLE
Is this version stable?

### ISSUE THREAD

**Issue by sakella1986** [flowable/flowable-mongodb#1]
HI there, I am looking for BPM which supports mongodb persistence. Looks like the last commit was 8 months ago so I would like to know how stable this code is to use?

**Comment by tijsrademakers** [comment]
Hi, we could test quite a number of BPMN processes successfully, including service tasks, user tasks, embedded sub processes etc. That was the point where we wanted to get feedback from the community. Until now the interest in running Flowable on MongoDB has been low, so it has not been the focus for a while. When there's enough interest we can prioritize it again.

**Comment by sivan123** [comment]
Would this come out of alpha?

**Comment by paulhh** [comment]
We're still waiting for more feedback from the community.  It woud be a great help if you tried it out and let us know if it works for your needs.

**Comment by willie68** [comment]
First of all, thanks for your work.
I'm on a task evaluating different db options for flowable, because we're just implementing flowable in one of our projects. First, we already have an mongodb in our setup, but for on-prem installations we don't want the hassel to introduce another database to our customer. (On a cloud setup that will be another question) So we are highly interested to base the engine persistence on mongo. 
I know that this is a alpha version, but how do you connect to an authorized mongo cluster? 
I'm just missing parameters like mongoUsername, pwd and authDB. (I just made an implementation in the MongoDbProcessEngineConfiguration.java)
Second: Is the storage for the Form Storage already implemented or is this one of the missing parts, like DMN or CMMN?
Is the tenant function implemented in the same way as in the other database stores?

**Comment by SanzarRehman** [comment]
Bring mongo support
